baseURL = 'https://diypedals.net'
languageCode = 'en-us'
title = 'diypedals.net'
theme = 'hugo-flex'

[markup.goldmark.renderer]
    unsafe = true

[params]
    color = "#0f0f13"
    width = "740px"
    css = ["diypedals.css"]
    footer = '&copy; diypedals.net &mdash; a community project'
